language: perl
sudo: false

addons:
  apt:
    packages:
      - liblzo2-dev
      - nettle-dev
      - libarchive-dev

install:
  - perlbrew list
  - ./maint/travis-install-mods
  - af missing --plugin | cpanm n
  - af missing | cpanm
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - dzil test -v

env:
  global:
    - ALIEN_BASE_NO_ABMB=1
    - ALIEN_BUILD_PRELOAD=Probe::OverrideCI
  matrix:
    - ALIEN_INSTALL_TYPE_CI=share
    - ALIEN_INSTALL_TYPE_CI=system
